#!/bin/bash

CUR_UID=$(id -u) CUR_GID=$(id -g) CUR_UN=$(id -un) CUR_GN=$(id -gn) docker compose run openwrt_builder bash
CUR_UID=$(id -u) CUR_GID=$(id -g) CUR_UN=$(id -un) CUR_GN=$(id -gn) docker compose down
